name: rustup

description: Install Rust toolchains

inputs:
  save-cache:
    default: false
    required: false
    type: boolean
  shared-key:
    default: 'check'
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Print Inputs
      shell: bash
      run: |
        echo 'save-cache: ${{ inputs.save-cache }}'
        echo 'shared-key: ${{ inputs.shared-key }}'

    - name: Get toolchain from rust-toolchain.toml
      id: rust-toolchain-toml
      shell: bash
      run: |
        CHANNEL=$(grep "channel" rust-toolchain.toml | cut -f 3 -d' ' | sed s/\"//g)
        echo "channel=$CHANNEL" >> "$GITHUB_OUTPUT"

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{steps.rust-toolchain-toml.outputs.channel}}

    - name: Cache on ${{ github.ref_name }}
      uses: Swatinem/rust-cache@v2
      if: ${{ startsWith(runner.name, 'GitHub Actions') }}
      with:
        shared-key: ${{ inputs.shared-key }}
        save-if: ${{ inputs.save-cache == 'true' }}