name: Node/pnpm workspace setup

description: |
  Install NodeJS and pnpm on the system, then install dependencies for the whole workspace. Any pnpm
  command in the repository can be run after this action has completed.

inputs:
  node-version:
    default: "20"
    required: false
    type: string
  frozen-lockfile:
    default: false
    required: false
    type: boolean
  save-if:
    default: false
    required: false
    type: boolean

runs:
  using: composite
  steps:
    # Install pnpm _first_ so that the setup-node action can use it for
    # restoring the cache.
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        # Don't install dependencies immediately, the node action below will
        # handle it and load from a cache appropriately.
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        # registry-url has to be set for the generated .npmrc to authenticate
        # and allow publishing.
        registry-url: 'https://registry.npmjs.org/'
        cache: pnpm