name: Node/pnpm workspace setup

description: |
  Install NodeJS and pnpm on the system, then install dependencies for the whole workspace. Any pnpm
  command in the repository can be run after this action has completed.

inputs:
  node-version:
    default: "20"
    required: false
    type: string
  frozen-lockfile:
    default: false
    required: false
    type: boolean
  save-if:
    default: false
    required: false
    type: boolean

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org/'

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        standalone: ${{ startsWith(inputs.node-version, '16') }}


    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        # set store-dir to $(pnpm config get store-dir)/$(pnpm -v)
        global_store_path=$(pnpm config get store-dir)
        if [ -z "${global_store_path}" ] || [ "${global_store_path}" = "undefined" ]; then
          global_store_path=~/.cache/pnpm
        fi
        pnpm config set store-dir $global_store_path/$(pnpm -v) --location project
        echo "STORE_PATH is $(pnpm store path)"
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Install dependencies
      shell: bash
      run: |
        if [[ "${{ inputs.frozen-lockfile}}" == 'true' ]]; then
          pnpm install --frozen-lockfile --prefer-offline
        else
          pnpm install --no-frozen-lockfile --prefer-offline
        fi