[package]
name = "intl_markdown_macros"
description = "Procedural macros for intl_markdown"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
convert_case = "0"
proc-macro2 = "1"
quote = "1"
syn = "2"