[package]
name = "intl_markdown_visitor"
description = "AST visitor utility traits and implementations for intl_markdown"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
intl_markdown = { workspace = true }
