[package]
name = "intl_message_utils"
description = "Utilities used across different crates in the intl package."
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
xxhash-rust = { workspace = true }
memchr = { workspace = true }
once_cell = { workspace = true }