[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

# Compiling cdylib on musl requires negating crt-static
[target.'cfg(target_env = "musl")']
rustflags = ["-C", "target-feature=-crt-static"]

[target.aarch64-unknown-linux-gnu.env]
CC_aarch64_unknown_linux_gnu = "clang"

[target.aarch64-unknown-linux-musl.env]
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER = "aarch64-linux-musl-gcc"

[target.x86_64-unknown-linux-musl.env]
CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER = "x86_64-linux-musl-gcc"

[target.aarch64-apple-darwin.env]
MACOSX_DEPLOYMENT_TARGET = "11"

[target.x86_64-apple-darwin.env]
MACOSX_DEPLOYMENT_TARGET = "10.13"