[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-apple-darwin.env]
MACOSX_DEPLOYMENT_TARGET = "11"

[target.x86_64-apple-darwin.env]
MACOSX_DEPLOYMENT_TARGET = "10.13"