name: Build intl-message-database

on:
  workflow_call:
    inputs:
      target: # Target triple for building the crate
        required: true
        type: string
      package-name: # npm package name that the target maps to
        required: true
        type: string
      runner:
        required: true
        type: string
      profile: # Rust profile, "debug" or "release"
        default: "release"
        required: false
        type: string
      ref: # Git reference to checkout
        required: false
        type: string

env:
  # This should ensure that the mac packages are allowed to run on all
  # supported macOS versions.
  MACOSX_DEPLOYMENT_TARGET: "10.13"

jobs:
  build:
    name: Build intl-message-database
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash
    outputs:
      runner-labels: ${{ steps.upload-artifact.outputs.runner-labels || inputs.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          clean: true

      - name: Setup Build Env
        uses: ./.github/actions/setup-build-env
        with:
          ref: ${{ inputs.ref }}
          runner: ${{ inputs.runner }}
          target: ${{ inputs.target }}

      - name: Build intl-message-database
        run: |
          pnpm intl-cli db build --target ${{inputs.target}}

      - name: Publish ${{inputs.package-name}}
        run: |
          pnpm intl-cli db publish --dry-run --target ${{inputs.target}}

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: intl-message-database-${{ inputs.package-name }}
          path: intl_message_database/npm/${{ inputs.package-name }}/**
