name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: 'Commit SHA'

permissions:
  # To publish packages with provenance
  id-token: write

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false # Build and test everything so we can look at all the errors
      matrix:
        target:
          # Linux
          - ['ubuntu-latest', 'linux-x64-gnu']
          - ['ubuntu-latest', 'linux-arm64-gnu']
          - ['ubuntu-latest', 'linux-x64-musl']
          - ['ubuntu-latest', 'linux-arm64-musl']
          # Windows
          - ['windows-latest', 'win32-ia32-msvc']
          - ['windows-latest', 'win32-x64-msvc']
          - ['windows-latest', 'win32-arm64-msvc']
          # macOS
          - ['macos-latest', 'darwin-x64']
          - ['macos-latest', 'darwin-arm64']
    uses: ./.github/workflows/build-intl-message-database.yaml
    with:
      # Using napi and cargo-zigbuild/cargo-xwin, everything _should_ be buildable on ubuntu directly.
      runner: ${{ matrix.target[0] }}
      target: ${{ matrix.target[1] }}
      ref: ${{inputs.commit}}
    secrets: inherit
