name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        required: true
        type: string
        description: 'Commit SHA'

permissions:
  # To publish packages with provenance
  id-token: write

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false # Build and test everything so we can look at all the errors
      matrix:
        target:
          # Linux
          - linux-x64-gnu
          - linux-arm64-gnu
          - linux-x64-musl
          - linux-arm64-musl
          # Windows
          - win32-ia32-msvc
          - win32-x64-msvc
          - win32-arm64-msvc
          # macOS
          - darwin-x64
          - darwin-arm64
    uses: ./.github/workflows/build-intl-message-database.yaml
    with:
      # Using napi and cargo-zigbuild/cargo-xwin, everything _should_ be buildable on ubuntu directly.
      runner: ubuntu-latest
      target: ${{ matrix.target }}
      ref: ${{inputs.commit}}
    secrets: inherit
